### ISSUE TITLE
Implement and set form statuses.

### ISSUE THREAD

**Issue by dkennedy881** [ecare-software/ecare-residential#154]
Add “status” property to all form modals. 

Set the status of the form to “IN PROGRESS” when save is selected and “COMPLETED” when submit is selected.

**Comment by Nerajno** [comment]
<img width="624" alt="Screenshot 2023-07-03 at 3 59 22 PM" src="https://github.com/ecare-software/ecare-residential/assets/18251846/b3506c8d-d1b1-4d26-b8ad-3e05ca180661">

**Comment by Nerajno** [comment]
- Creating the additional field [ created / completed ] on the form that created the form ( not displayed ).

**Comment by annastasiablack** [comment]
@dkennedy881 

COMPLETED:
* Added 'status' state to each form 
* Added 'status' to each form schema 
* 'Submit' button → 'Submit Without Saving' for clarity (discuss this, could also be labeled 'Save For Later')
* Form status = 'IN PROGRESS' until user clicks 'Save' button, then status = 'COMPLETED'
* Added 'Status' column to report overview table for demo purposes only (displaying status is out of scope on this ticket)

QUESTION:
*   Currently, when user clicks a form from the report overview table and routed to the editable form view, only the 'Save' button is showing. Let's discuss this.

<img width="796" alt="image" src="https://github.com/ecare-software/ecare-residential/assets/58446979/ff0ac4fe-d250-4b67-9ce0-5c2b42fc6016">
<img width="477" alt="image" src="https://github.com/ecare-software/ecare-residential/assets/58446979/bae46381-0e2c-4f3f-b564-07ba9dc7d26b">
