### ISSUE TITLE
Create a new view for client incident reports

### ISSUE THREAD

**Issue by dkennedy881** [ecare-software/ecare-residential#238]
We need a way to show a span of incidents for a specific child/client

the user should be able to:
- Select the client the want the incident summary for
- pick a date range 
- print the list of results

The print out should show the following
-- Field names
-- Explanation of the incident 
-- When did it happen

**Comment by dkennedy881** [comment]
@tydangelo18 
Comment here when you have an idea. we can set up a call to go over the UI and functional design

**Comment by tydangelo18** [comment]
@dkennedy881 is there an api already set up to handle this? Do we have a wire frame for how this should be presented? Is this basically a summarized version of an incident report for a single client?

**Comment by dkennedy881** [comment]
@tydangelo18 

Is there an api already set up to handle this? 
- Not technically. There isn't a new form, rather a different view of the incident report (less fields displayed).
- There is an api to pull incident reports based on filters (created date, the target client ect)

Do we have a wire frame for how this should be presented?
- No, but we have the real representation of what it should be based on

Is this basically a summarized version of an incident report for a single client?
- Yes, but say it like, this basically a summarized version of an incident reports, so show multiple, for a single client. depending of span of time.

**Comment by annastasiablack** [comment]
@dkennedy881 While adding headers to the report views, I realized Incident Report was displaying the 'created' date/time, not the 'incident occurrence' date/time. 
Today I:
- added a bootstrap table to the report view & worked on formatting
- added some conditions to check form type and display 'incident occurred' date & time for Incident Report
- matched the date/time format of 'incident occurrence' to match the other forms
Total time spent: 2 hours

**Comment by annastasiablack** [comment]
Added print by form type button above table.
Print functionality is on a different branch.
https://github.com/ecare-software/ecare-residential/tree/feature/print-reports-by-form-type

**Comment by annastasiablack** [comment]
- Added functionality to 'Print [form type] Forms' button above table
- Enhanced formatting for 'Printing [form type] Forms' spinner 

<img width="997" alt="image" src="https://github.com/ecare-software/ecare-residential/assets/58446979/18d08579-13be-479f-807a-c8742b266ed8">

<img width="608" alt="image" src="https://github.com/ecare-software/ecare-residential/assets/58446979/6a511396-6311-420e-b9e6-025d16c12710">

<img width="954" alt="image" src="https://github.com/ecare-software/ecare-residential/assets/58446979/17384437-7d21-4fc4-81be-d6cc3ade0811">
