### ISSUE TITLE
Enhance form list table

### ISSUE THREAD

**Issue by dkennedy881** [ecare-software/ecare-residential#291]
In the view that shows the list of forms:

the forms daily progress, serious incident, restraint report, and incident report should show
- the create date (without time)
- submitter name
- the client name
- (incident date/restraint date).

The rest of the forms should show
- the create date (without time)
- submitter name
- the client name.

**Comment by annastasiablack** [comment]
@dkennedy881 some questions: 

1. Are you sure the 'incident/restraint date' should show for Daily Progress & Activity form? I'm not seeing a date on the form other than 'create date'.
2. Should 'incident/restraint explanation' show for Serious Incident Reports, Restraint Reports, & Incident Reports?

**Comment by annastasiablack** [comment]
branch: https://github.com/ecare-software/ecare-residential/tree/update-report-table

![Untitled](https://prod-files-secure.s3.us-west-2.amazonaws.com/ad4c08f1-6443-4169-976f-1d1b64f13681/12d6ce18-ca84-499d-8bcc-01650a196f4a/Untitled.png)

![Untitled](https://prod-files-secure.s3.us-west-2.amazonaws.com/ad4c08f1-6443-4169-976f-1d1b64f13681/caba93c8-a74e-4aea-9dcd-56139e17708a/Untitled.png)

![Untitled](https://prod-files-secure.s3.us-west-2.amazonaws.com/ad4c08f1-6443-4169-976f-1d1b64f13681/83fd58b4-d12a-4641-82f9-4f699274c350/Untitled.png)

![Untitled](https://prod-files-secure.s3.us-west-2.amazonaws.com/ad4c08f1-6443-4169-976f-1d1b64f13681/a86f2a41-0a98-495a-8bfa-c436dcf10795/Untitled.png)
